version: "3"
services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/nginx.prod.Dockerfile
      args:
        - PROJECT_PATH=${PROJECT_PATH:-./src}
    restart: unless-stopped      
    depends_on:
      - template-gen
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/dynamic-configs:/etc/nginx/custom_templates
      - ./docker/nginx/static-configs:/etc/nginx/static-configs
      - ./docker/nginx/certs:/etc/nginx/certs
    ports:
      - ${WEB_PORT_HTTPS}:443
      - ${WEB_PORT_HTTP}:80
    env_file:
      - .env.prod
    working_dir: /var/www/app
  
  template-gen:
    build:
      context: .
      dockerfile: docker/template-gen/template-gen.Dockerfile
    volumes:
      - ./docker/nginx/dynamic-configs:/var/www/app/template-gen/output
      - ./docker/template-gen/templates:/var/www/app/template-gen/templates
      - ./docker/template-gen/src:/var/www/app/template-gen/src
    env_file:
      - .env.prod
