version: "3"
services:
  nginx:
    build:
      context: .
      dockerfile: docker/pc/pc.Dockerfile
      args: 
        COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME}
        PROJECT_PATH: ${PROJECT_PATH}/pc/
        APP_PORT: ${PC_APP_PORT}
    environment:
      - NODE_ENV=${NODE_ENV}
      - MOBILE_APP_URL=${MOBILE_APP_URL}
    ports:
      - "${PC_APP_PORT:-8081}:80"
    env_file:
      - .env
    volumes:
      - ./docker/pc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/pc/nginx/default.conf.template:/etc/nginx/templates/default.conf.template
    working_dir: /usr/share/nginx/html
